### PR TITLE
chore: remove translation

### PR DESCRIPTION
**Pull request by erisu**
### Motivation and Context

See #995

### Description

- Removes Translated Docs

closes: #995
closes: #932
closes: #841
closes: #759
closes: #742
closes: #735

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've deleted documentation that is necessary

### CODE REVIEW

**Comment by dblotsky** [comment]
The ask in the issue was to remove translations, but not versions. Do we have proof that nobody uses Cordova < 5.4.0?

Dmitry

**Comment by janpio** [comment]
What happens to the old URLs - are they redirected to `latest`? Error message with proper 404 or 410?

**Comment by erisu** [comment]
@dblotsky 

Sadly, telemetry did not exist in 5.4.0 or lower so I can not tell you for certain whats the % of users that uses 5.4.0 or less. Here is an example of what I see from the data we do have.

**New Users (Sep 5th, 2019)**
5.x => ???
6.5.0 => 1,673 (2%)
7.x => 8,065 (10%)
8.x => 21059 (25%)
9.x => 53,069 (63%)


**Users out of 17,406 (Sep 3rd, 2019)**
5.x => ???
6.5.0 => 2.06%
7.x => 7.63%
8.x => 32.54%
9.x => 57.22%

If there was users still using 5.x and we throw that into the mix, I am guess it would be 1% or less.

**Comment by erisu** [comment]
@dblotsky 

In the original ticket, after you raised up the concern, one of @raphinesse replies contained:

> We should not put any effort into supporting old versions of Cordova let alone 10 translations of their docs.

I kinda took this into account and also removed versions but kept only a few based on the telemetry data. 

If other are as well wanting to keep all versions or add back a few more versions back, I can update. This is why I did the deletion of versions as a separate commit in this PR to easily delete or update if necessary.

**Comment by erisu** [comment]
Here is also the telemetry link for reference: http://telemetry.cordova.io

**Comment by raphinesse** [comment]
Well, then let's just remove the translations first. We can figure out what we do about those old versions later.

Thanks for taking care of this, @erisu.

**Comment by erisu** [comment]
Redirects to 404

**Comment by dblotsky** [comment]
Redirecting to 404 would be a pretty awful experience.

There is a bit of process for obsoleting pages: https://github.com/apache/cordova-docs/blob/master/doc/redirects.md.

But, I think obsoleting all translations is a big enough deal that we should:
1. Announce it (e.g. in a blog post),
2. Come up with a new redirect page specific for language deprecation (preferably in that language).
3. Have a roadmap for adjusting the build system not to build for all those languages.

**Comment by janpio** [comment]
> Come up with a new redirect page, specifically for language deprecation.

Here it would probably make sense to redirect to the EN version of everything.

**Comment by dblotsky** [comment]
We have a deprecation page in many languages. We can use those at the very least. But, what do you guys think, from a user experience perspective, of a custom message in each language explaining why we decided to remove translations?

**Comment by raphinesse** [comment]
Regarding your requested for changes @dblotsky:

> Redirecting to 404 would be a pretty awful experience.

Agreed.

> I think obsoleting all translations is a big enough deal that we should:
> 1. Announce it (e.g. in a blog post),

That would definitely be great to have.

> 2. Come up with a new redirect page, specifically for language deprecation.

Here I would go with what @janpio proposed:

> Here it would probably make sense to redirect to the EN version of everything.

I think this is more helpful than a redirect to a deprecation message. And it's very easy to implement. The following snippet added to [`www/.htaccess`](https://github.com/apache/cordova-docs/blob/d0890966b46655bbdeb8f2bf980b09a1f5bef525/www/.htaccess#L75) _should_ do the job (_untested_):

```apache
# Redirect all docs translations to their English version
RewriteCond $1 !=en
RewriteRule ^.*docs/(\w\w(?:-\w\w)?)/(.*)$ {{site.baseurl}}/docs/en/$2 [R=301,L]
```

> 3. Have a roadmap to change the build system not to build for all those languages.

IMHO, that is a matter of creating an issue titled _Remove language support from build system_ but should not block us from going live with these changes. It can be addressed when someone finds the time to do so.

**Comment by brodybits** [comment]
Any suggestions how we can move this forward?

Anything that I can do?

**Comment by dblotsky** [comment]
@brodybits sorry for the delay, and thank you for patience!

I think the best way forward is the one that's easiest to review: so, as few changes at a time as possible.

I propose this plan (possibly as 4 sequential PRs, with a week between each):
1. Announcing the deprecation in a blog post,
2. Adding the redirects, deprecation pages, etc.,
3. Actually deleting the translated pages (since the redirects made them unreachable), and
4. Deleting the code that supports translations.

What do you think?

**Comment by erisu** [comment]
Closing, build or deploy performance at this time is not a priority.

**Pull request closed without merging**
