### PR TITLE
CB-11946 - Blog post for Node 0.x and 4.x deprecation timelines

### PR DESCRIPTION
**Pull request by shazron**

### CODE REVIEW

**Comment by shazron** [comment]
screen shot 2016-10-03 at 4 21 22 pm

(timeline image links to itself, for a larger view)

**Comment by purplecabbage** [comment]
LGTM! 👍  :shipit:

**Comment by ryanjsalva** [comment]
+1 Ship it.

**Comment by kerrishotts** [comment]
+1 LGTM :-)

**Comment by sosahvictor** [comment]
Thanks for putting this together, @shazron.
+1

**Pull request closed without merging**
