### PR TITLE
fix: Quasar tools logo

### PR DESCRIPTION
**Pull request by breautek**
### Platforms affected
Website

### Motivation and Context

The recently added quasar logo url is malformed. It appears the website will prefix the URL with a `/static/` path and does not accept absolute URLs like CDNs.

The image appears on the [Home Screen - Cordova Tools](https://cordova.apache.org/) section.

### Description

I've downloaded the `quasar.svg` file and added it to the repo along with the other tools image assets and updated the config to use it.

### Testing

I've ran the local web server to observe my changes did indeed fix the logo.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Review by NiklasMerz — APPROVED** [review]

**Review by timbru31 — APPROVED** [review]
A shame we can't display absolute URLs. We should do some website love!

**Comment by breautek** [comment]
> A shame we can't display absolute URLs. We should do some website love!

perhaps another PR that makes the template smarter! :sweat_smile:

**Comment by breautek** [comment]
Thanks for the reviews.

**Comment by breautek** [comment]
@NiklasMerz Do you know if merged PRs will automatically get applied to https://cordova.apache.org/ eventually, or does it require more human action?

**Comment by NiklasMerz** [comment]
CI runs automatically and deploys the website

It is building right now. The build may fail and we need to restart it: https://travis-ci.com/github/apache/cordova-docs/builds/204215810

**Pull request merged**
