### PR TITLE
Ajout de popvox.png

### PR DESCRIPTION
**Pull request by juspriet**
Added popvox.png for app showcase.

### CODE REVIEW

**Comment by dblotsky** [comment]
Hi @juspriet. Thank you for the PR! Please add a description for your app. The instructions to do this are here: https://github.com/apache/cordova-docs/tree/cordova-website#adding-a-tool-or-a-showcase-app.

**Comment by juspriet** [comment]
Hello ! Actually, i did ! But the two actions are uncorrelated, with two different tickets. Sorry for that !

**Comment by juspriet** [comment]
Hello ! Do I have to make the all procedure again or can you merge my two different commits ? Thank you for your answer

**Comment by juspriet** [comment]
The app description :
https://github.com/juspriet/cordova-docs/commit/0861d4c8a11c53aec5247de7647038671cadc477

**Pull request closed without merging**
