### PR TITLE
CB-12744: Misspelling in Config.xml documentation

### PR DESCRIPTION
**Pull request by johncblandii**
### Platforms affected

Documentation only.

### What does this PR do?

Fixed a misspelling in the documentation.

### What testing has been done on this change?

N/A

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by stevengill** [comment]
Thanks for the PR!

**Comment by johncblandii** [comment]
Is something wrong with merging it, @stevengill?

**Comment by stevengill** [comment]
no, it got merged. We use a bot that has to close the PRs since apache doesn't give us write access to these github mirrors so we can't close it manually.

Your commit on master: https://github.com/apache/cordova-docs/commit/e8ae4e4498f915b21876e7d045cdbb014489c365

**Comment by johncblandii** [comment]
Ah, I see. I forgot this was a mirror.

**Pull request closed without merging**
