### PR TITLE
CB-9295 Add GA analytics code on the Cordova Docs page

### PR DESCRIPTION
**Pull request by kant2002**
GA code added to all templates

### CODE REVIEW

**Comment by nikhilkh** [comment]
Looks like https://github.com/apache/cordova-docs/blob/master/template/docs/default/index.js already has GA code. We should just re-use it and add the correct the ID.

**Comment by nikhilkh** [comment]
Any ideas on how we can update older versions of the docs to use this new ID? Is it just a find and replace job?

**Comment by kant2002** [comment]
If I will use code in the index.js, we have to update only index.js files across all versions and we are all set. (not sure about very old (<2.0) English versions. I will move code from index.html to index.js. This should be enough.

**Comment by kant2002** [comment]
I also change from the old GA format to new. But we have to verify that both codes working. and as around about PhoneGap tracking code, do Adobe still use it?

One more thing which I could implement is add recording of events on following occasions
1. User change language
2. User select topic in the subheader select.

**Comment by nikhilkh** [comment]
We don't care about the old GA tracking ID - in fact we do not have a way to even access it. As for the custom events, I'm new to google analytics but since they lead to navigations which are also tracked in GA, not sure if there is much value in adding custom events.

**Comment by kant2002** [comment]
So if I could safely remove that old ID, I will do that. Any chance that somebody from Adobe has access and use it?

**Comment by nikhilkh** [comment]
@stevengill tried to find if anyone could get access to it, but did not find the correct owner.

**Comment by kant2002** [comment]
Ok, so I drop it.

**Comment by kant2002** [comment]
To update the file index.js should be distributed to all versions.

**Comment by nikhilkh** [comment]
I see - I can take a stab at updating all the older versions on the svn repo that has our website.

**Comment by nikhilkh** [comment]
I merged this one 2f620e6. I had a typo in my commit message and this PR remained open. Can you please close it?

**Comment by nikhilkh** [comment]
Thanks for the contribution!

**Pull request closed without merging**
