### PR TITLE
update Chinese translation on 7.x/guide/platforms/ios/config.md

### PR DESCRIPTION
**Pull request by situee**
fixed some Chinese (zh-cn & zh-tw) translation errors

### Platforms affected
/7.x/guide/platforms/ios/config.md

### What does this PR do?
fixed some Chinese translation errors

### What testing has been done on this change?
checked on preview

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Awesome. Don't expect a quick merge though, the situation around translations is a bit unclear right now. Normally Cordova uses Crowdin, an external service, to manage these, but the process got "lost" along the way and will have to be rebuilt. Then it can be decided if this can be merged directly or has to come from Crowdin (where the edits you made could just be manually copied over).

**Comment by situee** [comment]
I cannot find the file `config.md` at the path `/guide/platforms/ios/` on Crowdin.
How to add the English source of `/guide/platforms/ios/config.md` to Crowdin?

**Comment by janpio** [comment]
As I said, it is not clear if this would actually be useful.

Seems like the file is not mapped on Crowdin.

**Comment by janpio** [comment]
Actually, this file doesn't exist in current versions of the docs:
https://github.com/apache/cordova-docs/tree/master/www/docs/en/dev/guide/platforms/ios

**Pull request merged**
