### PR TITLE
Remove more unused stuff

### PR DESCRIPTION
**Pull request by raphinesse**
### Motivation and Context

During an effort of cleaning up the linting in this repo, I discovered that beside `tools/bin/` nothing inside `tools/` is actually used anywhere.

### Description

Removed unused modules, imports and dependencies

### Testing

I compared the output of `gulp build` before and after this change, to verify that the built website remains unchanged.

### CODE REVIEW

**Comment by janpio** [comment]
What was all this stuff for?

**Comment by raphinesse** [comment]
@janpio It all seemed to be part of the previous build system :man_shrugging:

**Comment by raphinesse** [comment]
https://github.com/apache/cordova-docs/commit/282c4019a82be95390e63feac28c529663e87c38#diff-b9e12334e9eafd8341a6107dd98510c9 introduced the currently used build system but simply left the old one in place, it seems.

**Comment by janpio** [comment]
AS I don't understand the curretn build process (and manual possible actions) very well, I am a bit scared to delete any of those files :/

**Comment by raphinesse** [comment]
Well I have little knowledge of the build myself. But the fact that I can build the website and docs without these files in `tools/lib` together with the fact that they are not referenced from anywhere in this repository makes me confident that they are utterly useless.

**Comment by raphinesse** [comment]
@dblotsky I have been doing clean builds and diffing them. What makes you think I did not verify that these files are actually unused? In fact, my last comment explicitly states that the removed files were not referenced from anywhere in this repository.

**Comment by dblotsky** [comment]
Sorry, I only read the changes on my phone, where I saw the list of files under the title "Remove more unused stuff", and saw files like `tools/bin/toc.js` in the list. Because of this, I incorrectly assumed the files to be deleted, but they were only modified. I will take a second look at this PR and try building locally this evening, and will let you know if it all looks good on my end too!

**Comment by raphinesse** [comment]
Thanks for the clarification. Looking forward to your review, @dblotsky

**Comment by raphinesse** [comment]
Any news on this @dblotsky?

**Pull request merged**
