### PR TITLE
CB-10445: Documentation includes broken github links

### PR DESCRIPTION
**Pull request by sarangan12**
Fixing broken links.

@dblotsky @riknoll @nikhilkh @rakatyal Can you please review and merge this PR?

### CODE REVIEW

**Comment by nikhilkh** [comment]
LGTM. @rakatyal I remember we integrated a gulp command in docs build to find broken links - it might be a good idea to run it and fix all broken links. Also, we need it to be part of docs build CI.

**Comment by dblotsky** [comment]
Suggestion: use [reference-style links][ref].

[ref]: http://daringfireball.net/projects/markdown/syntax#link

**Comment by dblotsky** [comment]
@nikhilkh we have a [JIRA for it][jira], but it's lower priority.

[jira]: https://issues.apache.org/jira/browse/CB-10058

**Comment by riknoll** [comment]
@dblotsky that would be nice, but we don't really do that in the rest of the docs. Might be worth a separate JIRA task.

**Comment by sarangan12** [comment]
@dblotsky Changed the links to reference style links

**Comment by dblotsky** [comment]
@riknoll I've created [a JIRA][jira] for the styling.

[jira]: https://issues.apache.org/jira/browse/CB-10448

**Comment by dblotsky** [comment]
LGTM.

**Pull request closed without merging**
