### PR TITLE
Adding Gudog to apps showcase

### PR DESCRIPTION
**Pull request by javiercr**
Adding [Gudog](https://gudog.co.uk)'s mobile app to the apps showcase. 

Gudog was built with Cordova and Ionic and is available in UK, Germany, France and Spain for Android and iOS.

### CODE REVIEW

**Comment by dblotsky** [comment]
Hi @javiercr. Thank you for the PR! Is the app publicly available? I wasn't able to find a link to it.

**Comment by dblotsky** [comment]
Whoop, never mind me: found it!

**Comment by dblotsky** [comment]
Merged. Thanks for the PR! Feel free to close it and delete the branch.

**Comment by javiercr** [comment]
@dblotsky thank you! :)

**Comment by dblotsky** [comment]
You're welcome!

**Pull request closed without merging**
