### PR TITLE
Cb 10637

### PR DESCRIPTION
**Pull request by dhams**
Fixed link location which was previously not correct.

### CODE REVIEW

**Comment by riknoll** [comment]
@dhams Thanks for the PR! This is no longer an issue in master because the android `config.md` file was removed as part of the Android Guide improvements in 21afd07d1e14ff4b6dc524738ffaa4fc7594de1f. Would you mind closing this PR?

**Comment by dblotsky** [comment]
@dhams please close this PR when you have a moment.

**Comment by dhams** [comment]
closing this PR as that changes has already been covered.

**Comment by dblotsky** [comment]
@dhams thanks!

**Pull request closed without merging**
