### PR TITLE
Add ReactEurope App to Showcase

### PR DESCRIPTION
**Pull request by csantanapr**

### CODE REVIEW

**Comment by fredgalvao** [comment]
I couldn't find a link or any details about an app built with cordova there. Is an app in development?

**Comment by csantanapr** [comment]
Sorry about that @fredgalvao I changed the link to point to app in itunes

**Comment by fredgalvao** [comment]
Cool, @csantanapr! As an off-topic comment though, it'd be interesting to have a link to the companion app on the event website, I only found about it on the Medium post.

**Comment by dblotsky** [comment]
Sorry for the trouble, but is it possible to get a link that lead to both the Android and iOS apps?

**Comment by csantanapr** [comment]
@dblotsky found the correct website that list both platforms ios and android

**Comment by csantanapr** [comment]
This pull request is a mess, I close and try to do a new one

**Pull request closed without merging**
