### PR TITLE
Added Evothings Studio to Cordova Tools listing

### PR DESCRIPTION
**Pull request by mikaelkindborg**
Request to add info about Evothings Studio to the Cordova Tools section of the Cordova home page.

### CODE REVIEW

**Comment by mikaelkindborg** [comment]
Have you had the time to review this pull request for the Tools section of the Cordova home page? Is the format ok?

**Comment by dblotsky** [comment]
@mikaelkindborg thank you for submitting your app to the showcase! Sorry that it took us so long to address your PR. The Cordova developer community had a discussion that you can view [here][thread], and it was decided that the app showcase ought to be closed for submissions. Please however feel free to email dev@cordova.apache.org if you have any questions or concerns regarding this decision.

[thread]: http://markmail.org/message/xww4r34spb72h7r6

**Comment by mikaelkindborg** [comment]
@dblotsky Hi, I emailed the dev list as you suggested, but got no response as far as I can tell. Note that this pull request is not the app showcase, but for the tools section. Are you also rejecting additions to the tools section?

**Comment by jcesarmobile** [comment]
We are still discussing it, we'll let you know when something is decided.

**Comment by mikaelkindborg** [comment]
@jcesarmobile Thanks!

**Comment by mikaelkindborg** [comment]
@jcesarmobile Updated pull request with clarified description of Evothings Studio. What do you think?

**Comment by mikaelkindborg** [comment]
@dblotsky @jcesarmobile Hi, did you reach a decision regarding merging this pull request?

**Comment by dblotsky** [comment]
@mikaelkindborg I've merged the PR! Please feel free to close it. Somehow my merging script didn't append the "this closes..." part.

**Comment by mikaelkindborg** [comment]
@dblotsky Many thanks indeed for merging!

**Pull request closed without merging**
