### PR TITLE
CB-10560: Removing Amazon FireOS and Firefox OS from dev

### PR DESCRIPTION
**Pull request by riknoll**
I felt it was appropriate to make two separate commits. See [JIRA](https://issues.apache.org/jira/browse/CB-10560) for details

### CODE REVIEW

**Comment by riknoll** [comment]
@rakatyal @dblotsky @nikhilkh please review

**Comment by nikhilkh** [comment]
LGTM

**Comment by rakatyal** [comment]
LGTM

**Comment by dblotsky** [comment]
When this PR becomes merged, the support of FirefoxOS in Cordova will become an [unfeature].

[unfeature]: https://en.wikipedia.org/wiki/List_of_Newspeak_words#Unperson

**Pull request merged**
