### PR TITLE
update indexedDB iOS information 📲

### PR DESCRIPTION
**Pull request by mesqueeb**
Reference to https://github.com/apache/cordova-docs/issues/948

### CODE REVIEW

**Comment by erisu** [comment]
Was this change suppose to target only Cordova 8.x?

**Comment by mesqueeb** [comment]
I believe also v9

**Comment by Kepro** [comment]
why this simple PR is sitting here for almost one year? :(

**Comment by timbru31** [comment]
Closing in favor of the merged PR #1042. Thanks for your contribution!

**Pull request closed without merging**
