### PR TITLE
added android 5.1.0 release blog post

### PR DESCRIPTION
**Pull request by stevengill**
Please leave comments or send a PR with changes.

### CODE REVIEW

**Comment by riknoll** [comment]
Here's my blurb:

This update introduces a new API for Android plugin authors. Plugins that launch external activities can now better handle method calls on devices that are low on memory. In that scenario, the Android OS will sometimes kill the Cordova Activity when it is pushed into the background by the external Activity. This causes the plugin to lose any callbacks they have pending in the javascript. The new API allows the results of external Activity calls to be delivered via the `resume` event that is fired in the javascript after the Cordova Activity is destroyed and recreated. Plugin authors wishing to implement the new API should read the updated plugin guide [here](http://cordova.apache.org/docs/en/dev/guide/platforms/android/plugin.html).

Two core plugins support this new API and have been updated to fix longstanding bugs:

* cordova-plugin-camera@2.1.0 (fixes [CB-9189](https://issues.apache.org/jira/browse/CB-9189))
* cordova-plugin-contacts@2.0.1 (fixes [CB-10159](https://issues.apache.org/jira/browse/CB-10159))

Application authors are encouraged to update both their plugin and cordova-android versions to take advantage of these bug fixes. Please note that the aforementioned fixes require changes to your application as well. More information can be found in the READMEs of each of those plugins and in the new [Android lifecycle guide](http://cordova.apache.org/docs/en/dev/guide/platforms/android/lifecycle.html) that has been published to the Cordova documentation. This guide provides explanations and guidance on how to handle low memory scenarios on the Android platform as well as integrate the new resume APIs into your application.

**Comment by stevengill** [comment]
Great write up! Very detailed and informative. I'll add it to the blog soon.

**Comment by stevengill** [comment]
Added it to the blog post! Thanks!

**Comment by riknoll** [comment]
@stevengill great, thanks!

**Comment by infil00p** [comment]
LGTM!

**Comment by dhams** [comment]
Sorry guys but that not comes with the fixes ... Same #/CB-9189 is still there even after update 5.4.1

**Comment by riknoll** [comment]
@dhams you need to update your `cordova-android` platform to 5.1.0 and `cordova-plugin-camera` plugin to 2.1.0 to get the fix. Version 5.4.1 sounds like you are referring to a Cordova CLI version, which will not have pinned the new Android platform yet.

To check the version of `cordova-android` you have, try running the command `cordova platforms ls` in your project directory. You want to see `android 5.1.0` appear in the "Installed Platforms" list.

To check the version of `cordova-plugin-camera`, you have, try running the command `cordova plugin ls` in your project directory. You want to see `cordova-plugin-camera 2.1.0 "Camera"` appear in the output.

Let me know if that helps! Please also note that the fix is more involved than just updating the versions; the NullPointerException will go away, but you'll need to make some changes to your app to properly handle the Android lifecycle. Check out [this guide](https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/guide/platforms/android/lifecycle.md) for a more in depth discussion (sorry for the GitHub link, it hasn't been pushed to the website yet). There is an example app for the camera plugin that uses the fix at the end of that guide.

**Pull request closed without merging**
