### PR TITLE
CB-11550 Add android@5.2.1 release blog post

### PR DESCRIPTION
**Pull request by vladimir-kotikov**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
I think it's CB-11550

**Comment by vladimir-kotikov** [comment]
Thanks for pointing, @jcesarmobile. Updated.

**Comment by stevengill** [comment]
Can you also add a link to the 5.2.0 blog post since we never announced it. People might still want to see that changelog. http://cordova.apache.org/announcements/2016/07/02/android-5.2.0.html

**Comment by vladimir-kotikov** [comment]
@stevengill, added the link

**Pull request closed without merging**
