### PR TITLE
CB-10836 Improving "Edit" links

### PR DESCRIPTION
**Pull request by dblotsky**
# Changes

- Added links to Crowdin translation on appropriate pages
- Changed "Edit" links for translated content to point to English sources
- Changed "Edit" links for current content to point to /dev/ sources
- Changed all other "Edit" links point to their respective files

# Examples (link at each example's top)

### CODE REVIEW

**Comment by csantanapr** [comment]
@dblotsky Love the option to help with translations to get them to the right spot in Crowding.

Still I think the label for the button should be changed from "Edit" that was my initial concern. just Edit it's hard to spot and not knowing if it's going to login the user like the wiki

Can we have for English the button say "Edit Source on Github" and just be a Link, this way Link means you are going to leave this page and visit Gihub. Since there is one option.

Other Languages I would put two links "Edit Source on Gihub" and "Edit Translation on Crowding"

**Comment by stevengill** [comment]
LGTM

**Comment by dblotsky** [comment]
@csantanapr the links don't fit on mobile screens, which is why I went for a dropdown.

**Comment by csantanapr** [comment]
@dblotsky no way we can make it work on mobile float, flex, css, etc.. ?

**Comment by csantanapr** [comment]
They don't have to be on the row on mobile.

**Comment by dblotsky** [comment]
@csantanapr please take a look at #555. It has the links implementation and a screenshot of what it looks like on mobile.

**Comment by csantanapr** [comment]
@dblotsky  LGTM !

**Comment by dblotsky** [comment]
@csantanapr which of the two implementations do you think we should go for?

**Comment by csantanapr** [comment]
@dblotsky I vote for using links #555

**Comment by dblotsky** [comment]
Closing in lieu of #555.

**Pull request closed without merging**
