### PR TITLE
App showcase newvo

### PR DESCRIPTION
**Pull request by boblikesoup**
Added NewVo to the app showcase.  Folders/files were missing for app-showcase mentioned in the documentation so created them myself (though sample-apps did exist).  Unsure on the formatting of the yaml file.

### CODE REVIEW

**Comment by purplecabbage** [comment]
@boblikesoup (great name!) You broke github.
There are 19k modified files in the pull request, which implies to me that something is seriously wrong here.
@dblotsky What is the correct way to submit pr's for app showcase additions?
Should we setup a separate repo just for app-showcase pages? It does not seem to belong with documentation.

**Comment by dblotsky** [comment]
Naw, [it's fine](https://36.media.tumblr.com/488e6d8f3214f689725ea25140534924/tumblr_notbb5J6IA1qa9oovo1_400.jpg).  The PR is open against master, which is why it's complaining. I'll merge it into the `cordova-website` branch. That branch contains the new website/docs work, which is why it's so massive. Fear not: `cordova-website` will get squashed before merging into master.

**Comment by dblotsky** [comment]
Merged into the `cordova-website` branch. Feel free to close the PR.

**Comment by dblotsky** [comment]
Ping! Please close this PR.

**Pull request closed without merging**
