### PR TITLE
CB-10916 - Add documentation about display name

### PR DESCRIPTION
**Pull request by dpogue**
### What does this PR do?
Add documentation for `<name short="...">` to the config.xml reference page.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
This feature will be in cordova-ios@4.4.1 or 4.5.0 (confirm before pulling in)

**Comment by shazron** [comment]
This will be in 4.4.1

**Comment by janpio** [comment]
A bit late to the party, but where does this actually apply and work? (iOS, Android, Windows?)

**Comment by shazron** [comment]
@janpio Check out https://issues.apache.org/jira/browse/CB-10916 -- shows that two PRs to android and ios were pulled in for this feature.

**Pull request closed without merging**
