### PR TITLE
cordova-node-xcode@2.1.0 release notes

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

iOS, osx (macOS)

### Motivation and Context

release notes needed for upcoming xcode@2.1.0 release 

### Description

release notes for upcoming xcode@2.1.0 release, with external contributions

* Support watch2 apps/extensions ([#56](https://github.com/apache/cordova-node-xcode/pull/56))
* Update writeObjectsSections to match current Xcode format ([#46](https://github.com/apache/cordova-node-xcode/pull/46))

### Testing

quick visual inspection

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by brodybits** [comment]
Thanks guys for the quick review.

The one thing is that this release was *mostly* triggered by non-Cordova members. But yeah, probably not needed to state this:)

**Comment by erisu** [comment]
Ah OK, I understand, thanks for the clarification.

Thank you for tackling this release! As well to all the external contributors who put in the work behind this release!  🎉

**Comment by brodybits** [comment]
@erisu I just saw your private message on Slack, would appreciate it if you can help with the manual build. (I don't even know how to do it.) Thanks again!

**Comment by erisu** [comment]
It is now released and available on the website. 
https://cordova.apache.org/news/2019/12/24/xcode-release-2.1.0.html

**Pull request merged**
