### PR TITLE
replaced NewVo iamge in app showcase

### PR DESCRIPTION
**Pull request by boblikesoup**

### CODE REVIEW

**Comment by dblotsky** [comment]
Thanks for the PR! My only concern is that this image might not be visible very well in the 100px height it receives on the front page. Are you sure you want to use this image?

**Comment by boblikesoup** [comment]
I just resized it and it looks legible enough to me.  Thanks.

**Comment by dblotsky** [comment]
Hey @boblikesoup, sorry for the delay in addressing this! Would you please be able to submit an image that contains the app's logo only? We've drafted some [guidelines](https://github.com/apache/cordova-docs/tree/cordova-website#guidelines) for app icons so that they all match a bit and fit with the rest of the showcase section.

**Comment by dblotsky** [comment]
Merged. Thanks for the PR! Feel free to close it and delete the branch.

**Pull request closed without merging**
