### PR TITLE
Adding Search Button

### PR DESCRIPTION
**Pull request by dblotsky**
Uncommenting search icon and linking it to Google search.

### CODE REVIEW

**Comment by dblotsky** [comment]
@riknoll please review when you have a moment.

**Comment by riknoll** [comment]
@dblotsky That search icon is barely visible in the top right; I don't think people will notice it. Can we add a text input to make it easier to see and use? The icon also looks a bit awkward in the mobile nav menu. It adds itself to the expandable list and is the only non-text option there. I think that for a mobile screen, the search icon should stay in the top bar and appear to the left of the menu-expand icon (no need for a text input for mobile, it would just clutter the nav bar). Thoughts?

**Comment by dblotsky** [comment]
@riknoll I've incorporated your feedback. Please give it a look when you have a moment.

**Comment by dblotsky** [comment]
@riknoll and I've again updated the PR. Please give it a look when you have a chance. In particular, on `md` screens the search field disappears, and the search button now sticks to the right of the field.

**Comment by riknoll** [comment]
LGTM

**Pull request merged**
