### PR TITLE
Add Keyword Index back to the table of contents

### PR DESCRIPTION
**Pull request by riknoll**
Adds a translated keyword index page for each version of the docs that lists all the pages for that language/version. Page titles are scraped using toc.js

### CODE REVIEW

**Comment by riknoll** [comment]
@dblotsky can you review docs-keyword-index.js to make sure there aren't any security issues with how the page is taken from the Jekyll generated JSON and built?

**Comment by riknoll** [comment]
and the docs_index.html _include as well

**Comment by dblotsky** [comment]
Yep, LGTM. There is no user input, so there shouldn't be any security issues.

**Comment by dblotsky** [comment]
Feel free to close.

**Pull request closed without merging**
