### PR TITLE
Removing keyword index.

### PR DESCRIPTION
**Pull request by dblotsky**
It has been replaced by search.

### CODE REVIEW

**Comment by dblotsky** [comment]
@rakatyal @stevengill please review when you have a moment.

**Comment by stevengill** [comment]
Looks fine to me. 

I don't know the context behind the change though.

**Comment by rakatyal** [comment]
LGTM.

**Comment by dblotsky** [comment]
@stevengill just removing code that's not needed anymore. The search box at the top basically obsoletes it.

**Comment by nikhilkh** [comment]
LGTM

**Pull request merged**
