### PR TITLE
Update images.md

### PR DESCRIPTION
**Pull request by ttimmy**
### Platforms affected
Docs

### What does this PR do?
Add unofficial note to android icon docs.

### What testing has been done on this change?
I checked my android app and the icons now work as expected. The 6.0.0 version included the default cordova icons. No testing has been made for splash screens yet.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

CB-12221: (android) Fix documentation issue.

### CODE REVIEW

**Comment by shazron** [comment]
Has this been fixed in Cordova-Android 6.1.0?

**Comment by ttimmy** [comment]
It was. My change was rejected, see CB-12221

**Comment by jcesarmobile** [comment]
Yes @shazron, the icon problem is fixed in cordova-android 6.1.0

**Comment by purplecabbage** [comment]
closing

**Pull request closed without merging**
