### PR TITLE
CB-13349: Move "development" docs to /doc

### PR DESCRIPTION
**Pull request by janpio**
- Move "development" docs (install, Develop, Build, Deploy) to /doc
- Add a bit of crosslinking

I wasn't 100% sure about the file names, but "develop.md" or "deploy.md" felt too short. 
What do you think? Suggestions?

The README of course now is not very pretty and only a stepping stone before it can further be improved.

### CODE REVIEW

**Comment by dblotsky** [comment]
@janpio what's the overall motivator behind these changes? Is the goal to have all docs development info be separate from docs writing info?

**Comment by janpio** [comment]
Yes, first clean up and structure the current content (this PR), then work on grouping and improving it (as soon as this was merged).

**Comment by audreyso** [comment]
@dblotsky @janpio Hi! Is this ready to be merged? Will you be making any more changes? Thanks!

**Comment by janpio** [comment]
I think this is good to merge. But I would prefer if someone "reviewed" by checking and just telling me that I didn't mess up or lose anything.

**Comment by audreyso** [comment]
Yes I will review for you!

**Pull request closed without merging**
