### PR TITLE
Adding Framework7 to the tools list and Series Seven to the showcase

### PR DESCRIPTION
**Pull request by nolimits4web**
Adding information about Framework7 framework to the Cordova website
tools + Series Seven app to the Cordova website showcase

### CODE REVIEW

**Comment by nolimits4web** [comment]
Something went wrong, wanted to make separate PRs for app and tool. Let me know if it won't work and separate PRs are required

**Comment by dblotsky** [comment]
Both in one PR should be fine.

**Comment by dblotsky** [comment]
Merged. Thanks for the PR! Feel free to close it and delete the branch.

**Comment by nolimits4web** [comment]
Thanks

**Comment by dblotsky** [comment]
You're welcome!

**Pull request closed without merging**
