### PR TITLE
CB-14026 (android): Update Android SDK instructions

### PR DESCRIPTION
**Pull request by Menardi**
### Platforms affected
Android docs

### What does this PR do?
Updates the docs to give instructions on how to install the Android SDK in Android Studio, because `sdkmanager` has been discontinued, as per [CB-14026](https://issues.apache.org/jira/projects/CB/issues/CB-14026).

### Checklist
- [x] Commit message follows the format: "GH-3232: (android) Fix bug with resolving file paths", where GH-xxxx is the GitHub issue ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by dpogue** [comment]
[sdkmanager](https://developer.android.com/studio/command-line/sdkmanager) is still supported, and is the only way to install the Android SDK from the command-line. We should include it in our documentation.

**Comment by Menardi** [comment]
Ah! I was going on what the JIRA ticket said. I'll update the PR to include info on using `sdkmanager`.

**Comment by Menardi** [comment]
@dpogue I have updated this, do you think it's good to merge now?

**Comment by Menardi** [comment]
Thanks! As a more general Cordova repository question, is the general practice to wait for multiple reviews before merging? I am hoping to become more active in the project and am trying to learn the processes.

**Pull request merged**
