### PR TITLE
Updated "Sample Usage" in hooks/index.md

### PR DESCRIPTION
**Pull request by AKosmachyov**
### What does this PR do?

Updated "Sample Usage" of hooks.

### Checklist
- [ ] Commit message follows the format: "GH-3232: (android) Fix bug with resolving file paths", where GH-xxxx is the GitHub issue ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Was this broken before?

**Comment by raphinesse** [comment]
I successfully use `context.opts.platforms` in the `after_prepare` hook of `cordova-plugin-exclude-files`. I wouldn't rule out the possibility that this is different for different types of hooks though. In fact, I think I noticed that once. If that's the case, we should fix the inconsistency.

**Comment by AKosmachyov** [comment]
I've used it with the `after_plugin_install` and got the error "indexOf is not a function"

**Comment by raphinesse** [comment]
Just took a look at the code and can confirm that for `after_plugin_install`, platforms are at `opts.cordova.platforms`. IMHO, that also means that this PR is not the solution to our problem.

Instead, we should consolidate the contexts passed to the different hooks. Anyone know if there's documentation for that?

**Comment by raphinesse** [comment]
Hooks are handled in lib, so this should probably be converted into an issue for lib.

**Pull request closed without merging**
