### PR TITLE
CB-7185 - Document MediaPlaybackAllowsAirPlay iOS preference

### PR DESCRIPTION
**Pull request by shazron**
Pull in only when CB-7090 is complete.

### CODE REVIEW

**Comment by kant2002** [comment]
Hi @shazron, the CB-7090 is completed, maybe it is time to merge docs?

**Comment by shazron** [comment]
yup.

**Comment by shazron** [comment]
already merged in apache repo, github mirror is taking some time to propagate

**Comment by kant2002** [comment]
Please close this pull request, which is not auto closed.

**Pull request merged**
