### PR TITLE
Remove Windows occurrences from site "Create a Plugin"

### PR DESCRIPTION
**Pull request by GitToTheHub**
The windows platform is not supported anymore

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]

**Comment by breautek** [comment]
I think these improvements are good, especially since that windows link is actually a 404 as well.

The only thing is, the changes are made to dev which means they will apply on our next version snapshot, which is good but I think these changes also warrants being updated on our 12.x version of the docs as well. This can be done by mirroring the changeset on https://github.com/apache/cordova-docs/blob/master/www/docs/en/12.x/guide/hybrid/plugins/index.md file. This way when the PR is merged the change will be live on the current docs as well.

Would you like to do this?

**Comment by GitToTheHub** [comment]
No problem, I can do that 🙂

**Comment by GitToTheHub** [comment]
@breautek I reflected the changes to the 12.x docs and squashed the changes on the dev-docs to one commit

**Review by breautek — APPROVED** [review]

**Comment by breautek** [comment]
Awesome thanks!

**Pull request merged**
