### PR TITLE
Please add One Verse BIBLE app

### PR DESCRIPTION
**Pull request by ozexpert**
Hi, I've built the first BIBLE app using Cordova (so far I know).
Please take a look and add my beautifully crafted Cordova app on the official cordova website!

Thank you,
Young

### CODE REVIEW

**Comment by fredgalvao** [comment]
The url provided points to a server with no valid SSL certificate, and many browsers will warn users about that. Is there any problem changing that from `https` to `http`?

**Comment by ozexpert** [comment]
Hi, Yes please go a head with http. I've just made it to allow http traffic as well.

**Comment by ozexpert** [comment]
Hi, please add my app ~~ thank you :+1:

**Comment by ozexpert** [comment]
Hi, any progress on this?

**Comment by dblotsky** [comment]
Hi! Sorry for the delay: we've been tied up with a Cordova meeting for these last two days. I'll merge this PR today.

**Comment by dblotsky** [comment]
Hey @ozexpert: sorry, I've been having issues with the links. https://onever.se is not responding, and http://onever.se gives a 404. Has the URI changed?

**Comment by ozexpert** [comment]
I'm sorry i recently changed the domain but this should work

http://www.onever.se

**Comment by ozexpert** [comment]
I'll redirect http://onever.se -> to http://www.onever.se

**Comment by dblotsky** [comment]
Hi @ozexpert. We're in the middle of a major merge in the repo, so I unfortunately won't be able to do this merge today. Stay tuned, and I will revisit it next week.

**Comment by ozexpert** [comment]
Thanks for letting me know. That is fine with me ~ :-)

**Comment by ozexpert** [comment]
any progress on this?

**Comment by purplecabbage** [comment]
Documenting cordova code + usage is the priority.
Please be patient.

**Pull request closed without merging**
