### PR TITLE
CB-10707 Add OS X to platform support page

### PR DESCRIPTION
**Pull request by tripodsan**

### CODE REVIEW

**Comment by nikhilkh** [comment]
@tripodsan Can you please review the conflicts and see if this is still relevant?

**Comment by tripodsan** [comment]
@nikhilkh I updated the PR. it is still relevant.

**Comment by nikhilkh** [comment]
Could you please squash and do a force push to your topic branch? This will help in merging this PR.

**Comment by tripodsan** [comment]
done.

**Pull request closed without merging**
