### PR TITLE
CB-10516: Remove h3-h6 from showing up in docs ToC

### PR DESCRIPTION
**Pull request by sarangan12**
Removing h3-h6 from showing up in docs ToC

@dblotsky @riknoll @nikhilkh Can you please review and merge this PR?

### CODE REVIEW

**Comment by riknoll** [comment]
LGTM

**Comment by dblotsky** [comment]
I'm still a bit unconvinced that all H3 - H6 headings should be excluded from ToC across the board. This is specific to the reference pages, isn't it?

**Comment by riknoll** [comment]
No, I don't think it is. What special meaning does H3+ have in the TOC? All of our TOC entries for a page are presented without hierarchy in the sidebar; H3+ lose all meaning in that format and become semantically the same in importance as H2 in the TOC, which does not make sense.

**Comment by dblotsky** [comment]
Hmm, that's a good point. I guess if we ever do implement levels in the page ToC then we can always just put them back. LGTM then.

**Pull request closed without merging**
