### PR TITLE
CB-13523: Add automaticProvisioning to iOS signing docs

### PR DESCRIPTION
**Pull request by dpogue**
Docs side of https://github.com/apache/cordova-ios/commit/5cb8bd199fe8df85272678d6d4c6343dd080f2a3

Also tried to clean up the manual flags to indicate that automatic signing is generally recommended, and you should only need to specify a provisioningProfile UUID if you're using manual signing.

### Platforms affected
iOS

### What does this PR do?
Adds docs for the `--automaticProvisioning` option

### CODE REVIEW

**Comment by stevengill** [comment]
LGTM. @dpogue ready to merge or wait until after next iOS release?

**Comment by dpogue** [comment]
The `--automaticProvisioning` flag won't be available until the next iOS release

**Comment by dpogue** [comment]
This has now been released in Cordova-iOS 4.5.4 and can be merged

**Comment by surajpindoria** [comment]
Cool! Forgot about this PR, merging in!

**Pull request merged**
