### PR TITLE
Sitemap Improvements

### PR DESCRIPTION
**Pull request by dblotsky**
- Implementing sitemap.xml manually instead of using a plugin. 
- Adding /latest/ URIs to sitemap.xml. Moving some CSS from main.scss to _docs.scss.

### CODE REVIEW

**Comment by dblotsky** [comment]
@riknoll @nikhilkh please review.

**Comment by nikhilkh** [comment]
I'm curious what's the motivation for not using the plugin?

**Comment by dblotsky** [comment]
@nikhilkh The plugin does not support adding custom URIs to the sitemap, and extending it took more effort than just writing a templated config.xml.

**Comment by nikhilkh** [comment]
Fair enough - let's get it in!

**Pull request merged**
