### PR TITLE
Execute jekyll in the context of the bundle

### PR DESCRIPTION
**Pull request by zhangkaizhao**
Execute jekyll in the context of the bundle because jekyll is installed by bundle here.

### CODE REVIEW

**Comment by dblotsky** [comment]
This is a great feature that I had no idea about. Thank you, @zhangkaizhao, for contributing this piece of Ruby/Bundle knowledge!

**Comment by dblotsky** [comment]
@zhangkaizhao before we merge, please also add this to the Makefile.

**Comment by dblotsky** [comment]
@zhangkaizhao thanks for your contribution! If you are interested in contributing more to Cordova or other Apache projects, I recommend for you to sign the [Apache ICLA][icla]. In this case it didn't matter because this repo is not distributed, but for other repositories it might be required.

All the best!

[icla]: http://www.apache.org/licenses/#clas

**Comment by zhangkaizhao** [comment]
@dblotsky OK! Thanks for you suggestion.

**Pull request closed without merging**
