### PR TITLE
Snapshotting dev to 6.x.

### PR DESCRIPTION
**Pull request by dblotsky**
@nikhilkh @rakatyal @riknoll please give this a glance when you have a moment.

### CODE REVIEW

**Comment by riknoll** [comment]
This is just moving the docs over right? In that case LGTM (as far as I can review it)! Just make sure that #563 gets in before we publish

**Comment by dblotsky** [comment]
Yep, it's just that. Will re-do this once #563 gets merged.

**Comment by riknoll** [comment]
Do you have to redo it? That PR only affects index.js

**Comment by dblotsky** [comment]
@riknoll you're right, that PR didn't affect this. However in re-doing it I found out that snapshotting didn't cover ToC files, and I fixed that. All's well now, and the site's deployed.

**Pull request merged**
