### PR TITLE
Document lib-file for Android

### PR DESCRIPTION
**Pull request by mbektchiev**
Documents the behavior introduced with: https://github.com/apache/cordova-lib/pull/290

### CODE REVIEW

**Comment by dblotsky** [comment]
@mbektchiev thanks for the PR! Sorry that it took so long to get to it. Given that apache/cordova-lib#290 is closed, is this change still valid?

**Comment by mbektchiev** [comment]
@dblotsky The currently existing behavior of the `lib-file` element for Android hasn't been documented so far. I've modified the PR and think that it's worth merging it this way.

**Comment by shazron** [comment]
Hi, this PR needs a rebase.

**Comment by mbektchiev** [comment]
Done.

**Pull request merged**
