### PR TITLE
added version 6.x

### PR DESCRIPTION
**Pull request by stevengill**
Deleted 6.0.0

### CODE REVIEW

**Comment by dblotsky** [comment]
Could you please split this into two commits: one for the content changes and one for the build changes?

**Comment by stevengill** [comment]
@dblotsky how does that look?

**Comment by stevengill** [comment]
@dblotsky getting back to this. Should I wait for your redirect work to land or move forward with this?

**Comment by dblotsky** [comment]
@stevengill there isn't really any redirect work: it's just docs. When you're back to this PR, please rebase and address the comments.

**Comment by stevengill** [comment]
Opening a new PR since I moved this work to a branch

**Pull request closed without merging**
